import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  decodeToolApprovalEvent,
  decodeToolApprovalSnapshot,
  ToolApprovalDecodeError,
} from "../src/types/tool-approval-decoder.js";
import { decodeWsFrameJson } from "../src/types/user-question-decoder.js";
import type { ToolApprovalTerminalCode } from "../src/types/tool-approval.js";

const configuredBackendRoot = process.env["NON" + "CLAW_DIR"];
const backendRoot = configuredBackendRoot ?? "/home/loidinh/WS/nonclaw";
const fixturePath = join(backendRoot, "test-fixtures/contracts/g4-tool-approval-v1.json");
const fixtureBytes = readFileSync(fixturePath);
const fixture = JSON.parse(fixtureBytes.toString("utf8")) as {
  schema: string;
  version: string;
  states: string[];
  terminal_states: string[];
  safe_codes: string[];
  sample_pending_snapshots: unknown[];
  sample_events: unknown[];
  negative_outcome_vectors: Array<{
    code: string;
    synthetic_tool_result: string;
    has_live_capsule: boolean;
    next_action: string;
    skip_remaining_calls: boolean;
  }>;
  redaction_assertion: {
    policy: string;
    forbidden_keys: string[];
  };
};

describe("Rust-generated G4 tool-approval fixture handoff", () => {
  it("pins the backend-generated bytes without copying them into the sibling", () => {
    const hash = createHash("sha256").update(fixtureBytes).digest("hex");
    expect(hash).toBe("18e94d54cbe4cef4d3964c8c9c717385739236a3cdd173d6cd56504a6998f48d");
    expect(fixture.schema).toBe("nonclaw.g4.tool-approval-v1");
    expect(fixture.version).toBe("tool_approval.v1");
  });

  it("decodes every generated sample pending snapshot", () => {
    expect(fixture.sample_pending_snapshots.length).toBeGreaterThan(0);
    for (const rawSnapshot of fixture.sample_pending_snapshots) {
      const decoded = decodeToolApprovalSnapshot(rawSnapshot);
      expect(decoded.state).toBe("pending");
      expect(decoded.schema_version).toBe("tool_approval.v1");
      expect(decoded.risk).toBe("high");
      expect(decoded.redaction).toBe("metadata_only");
      expect(decoded.binding_digest).toMatch(/^[0-9a-f]{64}$/);
      expect(decoded.safe_summary).toBeDefined();
    }
  });

  it("decodes every generated sample event and parses via decodeWsFrameJson", () => {
    expect(fixture.sample_events.length).toBeGreaterThan(0);
    for (const rawEvent of fixture.sample_events) {
      const decoded = decodeToolApprovalEvent(rawEvent);
      expect(decoded.event).toBe("tool_approval.updated");
      expect(decoded.payload.redaction).toBe("metadata_only");
      expect(decoded.payload.state).toBe("pending");

      const frame = decodeWsFrameJson(JSON.stringify(rawEvent));
      expect(frame).toBeDefined();
      if (frame && frame.type === "event") {
        expect(frame.event).toBe("tool_approval.updated");
      }
    }
  });

  it("rejects forbidden redaction keys when injected into snapshots", () => {
    const baseSnapshot = fixture.sample_pending_snapshots[0] as Record<string, unknown>;
    for (const forbiddenKey of fixture.redaction_assertion.forbidden_keys) {
      const hostile = {
        ...baseSnapshot,
        [forbiddenKey]: "leaked_secret_or_raw_data",
      };
      expect(() => decodeToolApprovalSnapshot(hostile)).toThrow(ToolApprovalDecodeError);
    }
  });

  it("rejects private or extra fields in sample snapshots", () => {
    const baseSnapshot = fixture.sample_pending_snapshots[0] as Record<string, unknown>;
    const withPrivate = {
      ...baseSnapshot,
      lease_owner: "daemon-worker-1",
    };
    expect(() => decodeToolApprovalSnapshot(withPrivate)).toThrow(ToolApprovalDecodeError);
  });

  it("validates that all safe_codes from the fixture are known terminal codes", () => {
    const expectedSafeCodes: ToolApprovalTerminalCode[] = [
      "approval_denied",
      "approval_expired",
      "approval_cancelled",
      "approval_binding_drift",
      "approval_policy_drift",
      "approval_safe_summary_unavailable",
      "approval_resolver_unavailable",
      "approval_store_mismatch",
      "approval_config_mismatch",
      "approval_backend_unsupported",
      "approval_conflict",
      "approval_indeterminate",
    ];
    for (const code of fixture.safe_codes) {
      expect(expectedSafeCodes).toContain(code as ToolApprovalTerminalCode);
    }
  });
});
