import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  decodeUserQuestionEvent,
  decodeUserQuestionRequest,
  decodeUserQuestionSnapshot,
  decodeWsFrameJson,
} from "../src/types/user-question-decoder.js";

const configuredBackendRoot = process.env["NON" + "CLAW_DIR"];
const backendRoot = configuredBackendRoot ?? "/home/loidinh/WS/nonclaw";
const fixturePath = join(backendRoot, "test-fixtures/contracts/g3-user-question-v1.json");
const fixtureBytes = readFileSync(fixturePath);
const fixture = JSON.parse(fixtureBytes.toString("utf8")) as {
  schema: string;
  supported_kinds: string[];
  pending_details: unknown[];
  read_only_pending_details: unknown[];
  list_snapshots: unknown[];
  terminal_snapshots: unknown[];
  events: unknown[];
  waiting_for_input: unknown[];
  accepted_202: unknown[];
  duplicate: unknown[];
  backward: unknown[];
  gap: unknown[];
  reorder: unknown[];
  unsequenced_refetch: unknown[];
  sequence_vectors: Array<{ name: string; expected: string; frame: unknown }>;
  g4_like: unknown[];
  hostile: unknown[];
};

describe("Rust-generated G3 fixture handoff", () => {
  it("pins the backend-generated bytes without copying them into the sibling", () => {
    expect(createHash("sha256").update(fixtureBytes).digest("hex")).toBe(
      "59934e70487397288eb7acea1d0483e5f929fc1c87e40159359d83a266f2e927"
    );
    expect(fixture.schema).toBe("nonclaw.g3.user-question-v1");
    expect(fixture.supported_kinds).toEqual(["single_choice", "short_text", "multiline"]);
  });

  it("accepts every generated pending request and owner detail", () => {
    for (const detail of fixture.pending_details) {
      const decoded = decodeUserQuestionSnapshot(detail);
      expect(decoded.state).toBe("pending");
      expect(decoded.request).toBeDefined();
      expect(decoded.mutation_token).toMatch(/^[a-f0-9]{32}$/);
      decodeUserQuestionRequest(decoded.request);
    }
    for (const detail of fixture.read_only_pending_details) {
      const decoded = decodeUserQuestionSnapshot(detail);
      expect(decoded.request).toBeDefined();
      expect(decoded.mutation_token).toBeUndefined();
    }
  });

  it("accepts G3 event envelopes and keeps snapshot replacement authoritative", () => {
    for (const event of fixture.events) {
      expect(decodeUserQuestionEvent(event).event).toBe("user_question.updated");
    }
    expect(decodeWsFrameJson(JSON.stringify(fixture.waiting_for_input[0]))).toMatchObject({
      type: "res",
      version: "v1",
    });
    expect(fixture.accepted_202[0]).toMatchObject({ status: 202 });
  });

  it("keeps redaction and closed-kind vectors explicit", () => {
    for (const group of [fixture.list_snapshots, fixture.terminal_snapshots, fixture.events]) {
      const serialized = JSON.stringify(group);
      expect(serialized).toContain("metadata_only");
      expect(serialized).not.toContain('"answer"');
      expect(serialized).not.toContain('"mutation_token"');
      expect(serialized).not.toContain('"request"');
    }
    expect(
      fixture.g4_like.some((value) => JSON.stringify(value).includes('"kind":"approval"'))
    ).toBe(true);
    expect(fixture.hostile.length).toBeGreaterThan(0);
    expect(fixture.duplicate.length).toBeGreaterThan(0);
    expect(fixture.backward.length).toBeGreaterThan(0);
    expect(fixture.gap.length).toBeGreaterThan(0);
    expect(fixture.reorder.length).toBeGreaterThan(0);
    expect(fixture.unsequenced_refetch.length).toBeGreaterThan(0);
  });

  it("keeps sequence metadata in the envelope and explicit refetch hints unsequenced", () => {
    expect(fixture.sequence_vectors.map((vector) => vector.name)).toEqual([
      "duplicate",
      "backward",
      "gap",
      "reorder",
      "unsequenced",
    ]);
    expect(fixture.sequence_vectors.every((vector) => vector.expected === "refetch")).toBe(true);
    for (const group of [fixture.duplicate, fixture.backward, fixture.gap, fixture.reorder]) {
      const raw = group[0] as Record<string, unknown>;
      const decoded = decodeUserQuestionEvent(raw);
      expect(decoded.event_seq).toBe(raw.event_seq);
      expect(decoded.payload).not.toHaveProperty("event_seq");
    }
    const unsequenced = decodeUserQuestionEvent(fixture.unsequenced_refetch[0]);
    expect(unsequenced.event_seq).toBeUndefined();
    expect(unsequenced.payload.snapshot_refetch_required).toBe(true);
  });
});
